
class Coupon {
  final String id;
  final String userId;
  final String type;
  final String couponFor; // 'client' or 'all'
  final DateTime validUntil;
  final bool active;
  final DateTime createdAt;
  final DateTime updatedAt;

  const Coupon({
    required this.id,
    required this.userId,
    required this.type,
    required this.couponFor,
    required this.validUntil,
    required this.active,
    required this.createdAt,
    required this.updatedAt,
  });

  // Check if coupon is expired
  bool get isExpired => DateTime.now().isAfter(validUntil);

  // Check if coupon is valid (active and not expired)
  bool get isValid => active && !isExpired;

  // Create from JSON (from Supabase)
  factory Coupon.fromJson(Map<String, dynamic> json) {
    return Coupon(
      id: json['id'] as String,
      userId: json['user_id'] as String,
      type: json['type'] as String,
      couponFor: json['coupon_for'] as String? ?? 'client',
      validUntil: DateTime.parse(json['valid_until'] as String),
      active: json['active'] as bool,
      createdAt: DateTime.parse(json['created_at'] as String),
      updatedAt: DateTime.parse(json['updated_at'] as String),
    );
  }

  // Convert to JSON (for Supabase)
  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'user_id': userId,
      'type': type,
      'coupon_for': couponFor,
      'valid_until': validUntil.toIso8601String(),
      'active': active,
      'created_at': createdAt.toIso8601String(),
      'updated_at': updatedAt.toIso8601String(),
    };
  }

  // Convert to JSON for inserting (without id, created_at, updated_at)
  Map<String, dynamic> toInsertJson() {
    return {
      'user_id': userId,
      'type': type,
      'coupon_for': couponFor,
      'valid_until': validUntil.toIso8601String(),
      'active': active,
    };
  }

  // Copy with method for immutability
  Coupon copyWith({
    String? id,
    String? userId,
    String? type,
    String? couponFor,
    DateTime? validUntil,
    bool? active,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return Coupon(
      id: id ?? this.id,
      userId: userId ?? this.userId,
      type: type ?? this.type,
      couponFor: couponFor ?? this.couponFor,
      validUntil: validUntil ?? this.validUntil,
      active: active ?? this.active,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
    );
  }

  @override
  List<Object?> get props => [
    id,
    userId,
    type,
    couponFor,
    validUntil,
    active,
    createdAt,
    updatedAt,
  ];

  @override
  String toString() {
    return 'Coupon(id: $id, userId: $userId, type: $type, couponFor: $couponFor, validUntil: $validUntil, active: $active, isValid: $isValid)';
  }
}

// Example usage with Supabase:
/*
// Fetch coupons
final response = await supabase
    .from('coupons')
    .select()
    .eq('user_id', userId);

final coupons = (response as List)
    .map((json) => Coupon.fromJson(json))
    .toList();

// Insert coupon
final newCoupon = Coupon(
  id: '', // Will be generated by database
  userId: currentUserId,
  type: 'DISCOUNT_10',
  validUntil: DateTime.now().add(Duration(days: 30)),
  active: true,
  createdAt: DateTime.now(),
  updatedAt: DateTime.now(),
);

await supabase
    .from('coupons')
    .insert(newCoupon.toInsertJson());

// Update coupon
await supabase
    .from('coupons')
    .update({'active': false})
    .eq('id', couponId);
*/