// import 'dart:math';
// import 'package:flutter/material.dart';
// import 'package:get/get.dart';
// import 'package:mego_app/core/shared_models/models.dart';
// import 'package:supabase_flutter/supabase_flutter.dart';

// class TestOfferSimulator extends StatelessWidget {
//   final String rideRequestId;
  
//   const TestOfferSimulator({Key? key, required this.rideRequestId}) : super(key: key);

//   @override
//   Widget build(BuildContext context) {
//     return Scaffold(
//       appBar: AppBar(
//         title: const Text('Test Offer Simulator'),
//         backgroundColor: Colors.blue,
//         foregroundColor: Colors.white,
//       ),
//       body: Padding(
//         padding: const EdgeInsets.all(16.0),
//         child: Column(
//           mainAxisAlignment: MainAxisAlignment.center,
//           children: [
//             Text(
//               'Ride Request ID: $rideRequestId',
//               style: const TextStyle(fontSize: 16, fontWeight: FontWeight.bold),
//               textAlign: TextAlign.center,
//             ),
//             const SizedBox(height: 30),
//             ElevatedButton(
//               onPressed: () => _simulateOffer(),
//               style: ElevatedButton.styleFrom(
//                 backgroundColor: Colors.green,
//                 padding: const EdgeInsets.symmetric(horizontal: 40, vertical: 16),
//               ),
//               child: const Text(
//                 'Simulate Driver Offer',
//                 style: TextStyle(color: Colors.white, fontSize: 16),
//               ),
//             ),
//             const SizedBox(height: 20),
//             ElevatedButton(
//               onPressed: () => _simulateMultipleOffers(),
//               style: ElevatedButton.styleFrom(
//                 backgroundColor: Colors.orange,
//                 padding: const EdgeInsets.symmetric(horizontal: 40, vertical: 16),
//               ),
//               child: const Text(
//                 'Simulate 3 Random Offers',
//                 style: TextStyle(color: Colors.white, fontSize: 16),
//               ),
//             ),
//             const SizedBox(height: 20),
//             const Text(
//               'This screen is for testing purposes only.\nUse it to simulate driver offers for your ride request.',
//               textAlign: TextAlign.center,
//               style: TextStyle(color: Colors.grey),
//             ),
//           ],
//         ),
//       ),
//     );
//   }

//   Future<void> _simulateOffer() async {
//     try {
//       final supabase = Supabase.instance.client;
//       final random = Random();
      
//       // Generate random offer data
//       final offeredPrice = 15.0 + (random.nextDouble() * 30); // €15-45
//       final estimatedTime = 5 + random.nextInt(20); // 5-25 minutes
//       final driverId = 'driver_${random.nextInt(1000)}';
      
//       final offer = DriverOfferModel(
//         id: '', // Will be generated by Supabase
//         rideRequestId: rideRequestId,
//         driverId: driverId,
//         offeredPrice: offeredPrice,
//         estimatedTime: estimatedTime,
//         status: DriverOfferModel.statusPending,
//         offerExpiresAt: DateTime.now().add(const Duration(minutes: 5)),
//         createdAt: DateTime.now(),
//       );

//       await supabase
//           .from('driver_offers')
//           .insert(offer.toJson());

//       Get.snackbar(
//         'Success',
//         'Driver offer simulated! Price: €${offeredPrice.toStringAsFixed(2)}',
//         snackPosition: SnackPosition.BOTTOM,
//         backgroundColor: Colors.green,
//         colorText: Colors.white,
//       );

//     } catch (e) {
//       Get.snackbar(
//         'Error',
//         'Failed to simulate offer: ${e.toString()}',
//         snackPosition: SnackPosition.BOTTOM,
//         backgroundColor: Colors.red,
//         colorText: Colors.white,
//       );
//     }
//   }

//   Future<void> _simulateMultipleOffers() async {
//     for (int i = 0; i < 3; i++) {
//       await _simulateOffer();
//       await Future.delayed(const Duration(seconds: 2)); // Delay between offers
//     }
//   }
// }